### ISSUE TITLE
Use whitespace instead of commas in event file input

### ISSUE THREAD

**Issue by ehrenjn** [ehrenjn/Real-Time-Systems-Project#1]
I thought we could use CSV for saving events but it turns out the event file should actually contain:

"a time stamp, white space, an integer representing the floor on which the passenger is making a request, white space, a string consisting of either “up” or “down”, more white space, then an integer representing floor button within the elevator which is providing service to the passenger."

**Comment by Christopher-Wang** [comment]
Fixed in EventReader.java
